### ISSUE TITLE
Setting a stl_customTabTextLayoutId or stl_defaultTabBackground hides the indicator

### ISSUE THREAD

**Issue by vibhorB** [ogaclejapan/SmartTabLayout#58]
Hi
If I set stl_defaultTabBackground to any color, say Blue, it draws on top of the indicator bar.
Same way if I apply a stl_customTabTextLayoutId and set background of textview to blue color, that draws on top of indicator. In all these cases the indicator gets hidden. It looks like these properties are painted after painting the tab indicator which ends up hiding the indicator
Is this a known issue?

Thanks
Vibhor

**Comment by ogaclejapan** [comment]
Hi, @vibhorB 

Oh,,, sorry.
The current version is to be able to specify the background for touch feedback.

Background do you change for each tab?
If the same background, please specify in the background of the TabLayout.

**Comment by apradanas** [comment]
Hi @ogaclejapan 

I'm having the same issue. I set stl_defaultTabBackground to a selector for touch feedback `app:stl_defaultTabBackground="@drawable/bg_selector"`, and the indicator still gets hidden.

Here's my `bg_selector`:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/blue" android:state_pressed="true"/>
    <item android:drawable="@color/red"/>
</selector>
```
Is there something missing?

In my case, specify the background of the TabLayout isn't something I need. CMIIW, it won't work for touch feedback anyway.

Thanks

**Comment by apradanas** [comment]
Hi again @ogaclejapan 

So, I managed to fix my problem. I changed my `bg_selector`:
```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true" android:state_selected="true">
        <layer-list>
            <item android:bottom="5dp" android:drawable="@color/blue"/>
        </layer-list>
    </item>
    <item android:state_selected="true">
        <layer-list>
            <item android:bottom="5dp" android:drawable="@color/red"/>
        </layer-list>
    </item>
    <item android:state_pressed="true">
        <layer-list>
            <item android:bottom="1dp" android:drawable="@color/blue"/>
        </layer-list>
    </item>
    <item>
        <layer-list>
            <item android:bottom="1dp" android:drawable="@color/red"/>
        </layer-list>
    </item>
</selector>
```
Well, that's not an ideal solution, but at least fix my problem for now. The idea is to put offset at the bottom in order to make the bottom indicator visible. I have `app:stl_underlineThickness="1dp"` and `app:stl_indicatorThickness="5dp"`.

Anyway, I suspect the root cause is in `SmartTabLayout#populateTabStrip`, specifically ![tabStrip.addView(tabView);](https://github.com/ogaclejapan/SmartTabLayout/blob/master/library/src/main/java/com/ogaclejapan/smarttablayout/SmartTabLayout.java#L392). If the `tabView` (which is TextView) background was set to specific color, it would drawn above the `tabStrip`, so the `tabStrip`'s indicator would never visible. Maybe you should specify margin for the `tabView`.

Really hope you could fix this issue with the best solution.

Thanks

**Comment by ogaclejapan** [comment]
Hi, @vibhorB @apradanas 

Right now, 1.5.0 released : )

```xml
stl_drawDecorationAfterTab="true"
```

So, this issue it will close.
