### ISSUE TITLE
How to achieve equally spaced tabs while also having the selected one at the center.

### ISSUE THREAD

**Issue by Shivam101** [ogaclejapan/SmartTabLayout#88]
Hi,
I am trying to achieve a layout similar to the one used by Tinder i.e. https://blog.nus.edu.sg/mobileixd/files/2015/02/1-1g3mmmu.png

I am able to add equally spaced tab icons but they are all placed close together to the center of the screen. Alternately I am able to have equally spaced tabs but without the selected one at the center. 
How do I achieve a combination of both ? 
I am trying to achieve this with a transparent divider of some thickness, but am not able to achieve the required result. 

How do I achieve this kind of layout with the selected tab in the center and the other two at the extreme ends of the screen ?

Thanks!

**Comment by ogaclejapan** [comment]
Hi, @Shivam101 
Reply Sorry slower :(
Do you already resolved?

Use a custom layout, if possible the size of each tab to be the same as the screen width, it might be realized. Of course always in center.

However, I think that in order to match the size of the tab on the screen width, it is necessary to make you can either specify directly on the code, or a custom view.
